'use client'

import './globals.css'

export default function RootLayout({ children }) { 
  return (
    <html lang="en">
      <head>
        <title>GrabPay Web Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/icons/logo-grabpay.svg" />
      </head>
      <body>
        <div className='bg-[#F5F8FD] text-[#0C0C0C] py-7 px-5 min-h-screen'>
          {children}
        </div>
      </body>
    </html>
  )
}
